FROM nginx:alpine

# Copy the Angular app
COPY ./dist/App/browser /usr/share/nginx/html

# Create inline nginx configuration
#RUN echo 'server {' > /etc/nginx/conf.d/default.conf && \
 #   echo '    listen 80;' >> /etc/nginx/conf.d/default.conf && \
 #   echo '    server_name localhost;' >> /etc/nginx/conf.d/default.conf && \
 #   echo '    root /usr/share/nginx/html;' >> /etc/nginx/conf.d/default.conf && \
 #   echo '    index index.html;' >> /etc/nginx/conf.d/default.conf && \
 #   echo '    location / {' >> /etc/nginx/conf.d/default.conf && \
 #   echo '        try_files $uri $uri/ /index.html;' >> /etc/nginx/conf.d/default.conf && \
 #   echo '    }' >> /etc/nginx/conf.d/default.conf && \
 #   echo '}' >> /etc/nginx/conf.d/default.conf